# Corrected render.yaml based on Render Blueprint spec
services:
  - type: web
    name: n8n-latest # Changed from "n8n:latest" as colons can cause issues
    runtime: image
    image:
      url: docker.io/n8nio/n8n:latest
    plan: free
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        sync: false
      - key: N8N_BASIC_AUTH_USER
        sync: false
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false
    region: oregon
    healthCheckPath: /alive
    autoDeploy: true # 'autoDeployTrigger: commit' is also valid

databases:
  - name: Biltontobillion
    databaseName: biltontobillion
    user: biltontobillion_user
    plan: free
    region: oregon
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
    postgresMajorVersion: "17"
